spring.application.name=office-service

spring.datasource.url=jdbc:postgresql://auth-postgres:5432/office_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

